# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7587a7430ecb68dccb233f4daeaf2d0f4d3faaf2e166c05d2c91f2bad4b32571308d70486b18a431fbd49d0fce33edc075549b749189156cf7cb66c03c038ab3

test:
  secret_key_base: 68007ef326f8b4fbc32a5a8f26fc1d6a07470b4a137bf9747adc8915720fba7848957833ef16ef017773ea6a751ca4fe4a3456e270cb224eda03ec027706e5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
